name: TEDxHakata
favicon: null
layout_spectrum: 0.316319944569841
typography_spectrum: 0.2652778560295701
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9781135425437242
  lightness: 0.2815645036753267
  saturation: 0.7089232103899121
  rhythmicContrast: 0.6901657718699425
purpose: []
